// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Direction } from "../common.sol";

/**
 * @title IMyGameSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IMyGameSystem {
  function app__spawn(uint32 x, uint32 y) external;

  function app__move(Direction direction, bytes32 positionLeaf, bytes32[] calldata proof) external;

  function app__getLeafIndex(uint32 x, uint32 y) external view returns (uint32);
}
